apiVersion : apps/v1
kind: Deployment
metadata:
  name: "democluster-054b"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "democluster-054b"
  template:
    metadata:
      labels:
        app: "democluster-054b"
    spec:
      containers:
        - name: "democluster-054b"
          image: "patinsa23d30df.azurecr.io/democluster"
          ports:
          - containerPort: 80